# This is a basic workflow that is manually triggered

name: Auto Test Run

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        type: choice
        description: Choose one env name - dev | staging | prod | qa | hotfix
        required: true
        default: dev 
        options:
          - dev
          - staging
          - qa
          - hotfix
          - prod
      app_version:
        description: 'Please do not enter manually! Version of the application under test.'
        required: false
        type: string
        default: ""

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  findApplicationVersion:
    name: Find version of application.
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " App version is : ${{ github.event.inputs.app_version }}"
  # This workflow contains a single job called "greet"
  runtests:
    needs: [decideApplicationVersion]
    name: Run Tests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Environment is ${{ github.event.inputs.app_version }} || App Version is ${{ github.event.inputs.environment }}"
