# This is a basic workflow that is manually triggered

name: Auto Test Run

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        type: choice
        description: Choose one env name - dev | staging | prod | qa | hotfix
        required: true
        default: dev 
        options:
          - dev
          - staging
          - qa
          - hotfix
          - prod
      app_version:
        description: 'Please do not enter manually! Version of the application under test.'
        required: false
        type: string
        default: ""

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  findApplicationVersion:
    name: Find version of application.
    runs-on: ubuntu-latest
    outputs: 
      app_version: ${{steps.version.outputs.version}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            version = '${{ github.event.inputs.app_version }}'
            if (version){
              print('No need to find version, it is already given.')
              print('::set-output name=version::${version}')
            }
            else{
              print('Need to find version.')
              print('::set-output name=version::1.0.0')
            }
    # steps:
    #   - uses: actions/github-script@v5
    #     name: Set version
    #     id: version
    #     with:
    #       script: |
    #         const version = '${{ github.event.inputs.app_version }}'
    #         if(version != ''){
    #           console.log('No need to find version, it is already given.')
    #           console.log(`::set-output name=version::${version}`)
    #         }else{
    #           console.log('Need to find version.')
    #           console.log(`::set-output name=version::1.0.0`)
            }
  # This workflow contains a single job called "greet"
  runtests:
    needs: [findApplicationVersion]
    name: Run Tests for ${{needs.findApplicationVersion.outputs.app_version}} version
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Environment is ${{ github.event.inputs.environment }} || App Version is ${{needs.findApplicationVersion.outputs.app_version}}"
