# This is a basic workflow that is manually triggered

name: Auto Test Trigger

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  automated_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Trigger Auto Tests with version
      uses: benc-uk/workflow-dispatch@v1
      with:
          workflow: Auto Test Run
          token: ${{ secrets.WORKFLOW_TOKEN }}
          inputs: |
            {"app_version": "3.0.0",
            "environment": "dev" }
          ref: ${{ github.ref }}
    - name: Trigger Auto Tests without version
      uses: benc-uk/workflow-dispatch@v1
      with:
          workflow: Auto Test Run
          token: ${{ secrets.WORKFLOW_TOKEN }}
          inputs: |
            {"app_version": "",
            "environment": "dev" }
          ref: ${{ github.ref }}